pipeline:
  identifier: Build_CIsamples_PythonMenu_1717043048763
  name: Build PythonMenu
  orgIdentifier: default
  projectIdentifier: project2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1717039821137
        repoName: CIsamples/PythonMenu
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    shell: Sh
                    command: echo 'hello'
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
